on:
  label:
    types:
      - created
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "14.0"
      - name: Build CMake config
        run: |
            cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .
      - name: Build/Install Snowball
        run: |
            sh ./build_scripts/release.sh
            sudo make install
      - name: Runing unit tests
        run: |
            snowball test

